version: 0.2

phases:
  install:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      -  gcc app.c -o app
artifacts:
  files:
    - target/app.jar
